server:
  port: 8080
  host: "0.0.0.0"

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  name: auto_message_sender
  ssl_mode: disable

redis:
  host: redis
  port: 6379

webhook:
  url: "https://auto-message-sender-api.free.beeceptor.com"